name: child_tracker
description: "Child Tracker App"
publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_messaging: 15.1.6
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.4
  cloud_functions: ^5.4.0
  go_router: ^14.8.0
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  flutter_svg: ^2.0.17
  intl: 0.19.0
  cached_network_image: ^3.4.1
  bot_toast: ^4.1.3
  pinput: ^5.0.1
  reactive_forms: ^17.0.1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2

  flutter_native_splash: 2.4.4
  collection: ^1.18.0
  mime: ^2.0.0
  file_picker: ^10.1.2

  cupertino_icons: ^1.0.8
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#EDC842"
  # image: assets/images/logo-development.png
  branding: assets/images/splash_logo.png

  android_12:
    image: assets/images/android12_splash_logo.png
    icon_background_color: "#EDC842"


  web: false